# Generated by Django 4.2.4 on 2023-08-11 14:12

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creation_date",
                    django_jalali.db.models.jDateField(auto_now_add=True, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_family",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Province", models.CharField(blank=True, max_length=100, null=True)),
                ("City", models.CharField(blank=True, max_length=100, null=True)),
                ("customer_address", models.TextField(blank=True, null=True)),
                (
                    "Persian_year",
                    models.CharField(
                        choices=[
                            ("1394", "1394"),
                            ("1395", "1395"),
                            ("1396", "1396"),
                            ("1397", "1397"),
                            ("1398", "1398"),
                            ("1399", "1399"),
                            ("1400", "1400"),
                            ("1401", "1401"),
                            ("1402", "1402"),
                            ("1403", "1403"),
                            ("1404", "1404"),
                            ("1405", "1405"),
                            ("1406", "1406"),
                            ("1407", "1407"),
                            ("1408", "1408"),
                            ("1409", "1409"),
                        ],
                        default="1402",
                        max_length=4,
                    ),
                ),
                (
                    "Persian_month",
                    models.CharField(
                        choices=[
                            ("01", "فروردین"),
                            ("02", "اردیبهشت"),
                            ("03", "خرداد"),
                            ("04", "تیر"),
                            ("05", "مرداد"),
                            ("06", "شهریور"),
                            ("07", "مهر"),
                            ("08", "آبان"),
                            ("09", "آذر"),
                            ("10", "دی"),
                            ("11", "بهمن"),
                            ("12", "اسفند"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                ("Persian_day", models.CharField(default="01", max_length=2)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("Consumer", "Consumer"),
                            ("Distributor", "Distributor"),
                            ("Retailer", "Retailer"),
                            ("Other", "Other"),
                        ],
                        default="Consumer",
                        max_length=20,
                    ),
                ),
                ("accepted", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "complaint_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Product Quality", "Product Quality"),
                            ("Packaging", "Packaging"),
                            ("Price", "Price"),
                            ("Distribution", "Distribution"),
                            ("External Material", "External Material"),
                            ("Weight", "Weight"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "external_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Plastic", "Plastic"),
                            ("Glass", "Glass"),
                            ("Metal", "Metal"),
                            ("Paper", "Paper"),
                            ("Wood", "Wood"),
                            ("Hair", "Hair"),
                            ("Glue", "Glue"),
                            ("Sugar", "Sugar"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("complaint_description", models.TextField(blank=True, null=True)),
                (
                    "product_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Jelly Gum", "Jelly Gum"),
                            ("Marshmallow", "Marshmallow"),
                            ("Coffee", "Coffee"),
                            ("Bakeries", "Bakeries"),
                            ("Chocolate", "Chocolate"),
                            ("Gum", "Gum"),
                            ("Jelly Powder", "Jelly Powder"),
                            ("Angel Kiss", "Angel Kiss"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_price",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product_barcode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "Persian_production_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1394", "1394"),
                            ("1395", "1395"),
                            ("1396", "1396"),
                            ("1397", "1397"),
                            ("1398", "1398"),
                            ("1399", "1399"),
                            ("1400", "1400"),
                            ("1401", "1401"),
                            ("1402", "1402"),
                            ("1403", "1403"),
                            ("1404", "1404"),
                            ("1405", "1405"),
                            ("1406", "1406"),
                            ("1407", "1407"),
                            ("1408", "1408"),
                            ("1409", "1409"),
                        ],
                        default="1402",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "Persian_production_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "فروردین"),
                            ("02", "اردیبهشت"),
                            ("03", "خرداد"),
                            ("04", "تیر"),
                            ("05", "مرداد"),
                            ("06", "شهریور"),
                            ("07", "مهر"),
                            ("08", "آبان"),
                            ("09", "آذر"),
                            ("10", "دی"),
                            ("11", "بهمن"),
                            ("12", "اسفند"),
                        ],
                        default="01",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "Persian_production_day",
                    models.CharField(blank=True, default="01", max_length=2, null=True),
                ),
                (
                    "production_site",
                    models.CharField(
                        blank=True,
                        choices=[("Hashtgerd", "Hashtgerd"), ("Firuzkuh", "Firuzkuh")],
                        default="Hashtgerd",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "production_shift",
                    models.CharField(
                        blank=True,
                        choices=[("Day", "Day"), ("Night", "Night")],
                        default="Day",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "complaint_status",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Open"), (False, "Close")],
                        default=True,
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("under Process", "under Process"),
                            ("process review", "process review"),
                            ("No action", "No action"),
                        ],
                        default="under Process",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("action_description", models.TextField(blank=True, null=True)),
                (
                    "action_date",
                    django_jalali.db.models.jDateField(blank=True, null=True),
                ),
                (
                    "action_deadline",
                    django_jalali.db.models.jDateField(blank=True, null=True),
                ),
                (
                    "action_responsible",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gift",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
