# Generated by Django 4.2.4 on 2023-08-09 10:56

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("Complaint", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("complaint_category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ContactType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("contact_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalMaterial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("external_material", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GiftModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("gift_type", models.CharField(max_length=100)),
                ("gift_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionSite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("production_site", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("shift", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="complaint_date",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="complaint_result",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="gift_type",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="packaging_complaint",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="product_colors_complaint",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="product_name",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="product_shapes_complaint",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="thing",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="Customer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="Customer_phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="acceptance_status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="complaint_quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="product_batch",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="send_gift",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_code", models.CharField(max_length=100)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Complaint.productcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplaintSubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("complaint_subcategory", models.CharField(max_length=100)),
                (
                    "compliant_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Complaint.complaintcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComplaintAction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("action_date_persian", django_jalali.db.models.jDateField()),
                ("action_description", models.TextField(max_length=1000)),
                ("action_status", models.BooleanField(default=True)),
                ("action_result", models.TextField(max_length=1000)),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Complaint.complaint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.complaintcategory",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaint_subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.complaintsubcategory",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="contact_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.contacttype",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="external_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.externalmaterial",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.giftmodel",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="customer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.customertype",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="product_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="product_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Complaint.product"
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="production_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.shiftmodel",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="production_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.productionsite",
            ),
        ),
    ]
