# Generated by Django 4.2.4 on 2023-08-09 13:04

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("Complaint", "0003_user_alter_complaint_complaint_date_persian_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="complaint_date_persian",
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="production_site",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Complaint.productionsite",
            ),
        ),
    ]
